draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: ''
  footer_text: ''
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  glyph_urls:
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    tabler: https://raw.githubusercontent.com/tabler/tabler-icons/master/icons/outline/{}.svg
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&comma_excl': {t: ',', s: '!'}
    '&quote_under': {t: '''', s: _}
    '&hyphen_qmark': {t: '-', s: '?'}
    '&dot_dqt': {t: '.', s: '"'}
    '&fslh_bslh': {t: /, s: \}
    '&w_caps': {t: CapsWord}
    '&msc SCRL_UP': {t: '$$mdi:arrow-up$$', h: scroll}
    '&msc SCRL_DOWN': {t: '$$mdi:arrow-down$$', h: scroll}
    '&msc SCRL_LEFT': {t: '$$mdi:arrow-left$$', h: scroll}
    '&msc SCRL_RIGHT': {t: '$$mdi:arrow-right$$', h: scroll}
    '&mmv MOVE_UP': {t: '$$mdi:arrow-up$$', h: mouse}
    '&mmv MOVE_DOWN': {t: '$$mdi:arrow-down$$', h: mouse}
    '&mmv MOVE_LEFT': {t: '$$mdi:arrow-left$$', h: mouse}
    '&mmv MOVE_RIGHT': {t: '$$mdi:arrow-right$$', h: mouse}
    '&mkp LCLK': {t: M1, h: mouse}
    '&mkp RCLK': {t: M2, h: mouse}
    '&mkp MCLK': {t: M3, h: mouse}
    '&semi_colon': {t: ';', s: ':'}
    '&kp LC(LA(LEFT))': {t: '$$mdi:arrow-left-bold$$', s: WS}
    '&kp LC(LA(RIGHT))': {t: '$$mdi:arrow-right-bold$$', s: WS}
    '&kp C_POWER': {t: '$$mdi:power$$'}
    '&mkp MB4': {t: M4, h: mouse}
    '&mkp MB5': {t: M5, h: mouse}
    '&kp LC(LEFT)': {t: Word ‚Üê}
    '&kp LC(RIGHT)': {t: Word ‚Üí}
    '&kp LC(Y)': {t: Redo}
    '&kp LC(F)': {t: Find}
    '&kp LG(LS(LBKT))': {t: Tab ‚Üê}
    '&kp LG(LS(RBKT))': {t: Tab ‚Üí}
    '&kp LG(Z)': {t: Undo}
    '&kp LG(X)': {t: Cut}
    '&kp LG(C)': {t: Copy}
    '&kp LG(V)': {t: Paste}
    '&kp LG(A)': {t: Sel All}
    '&kp LG(S)': {t: Save}
    '&kp LA(BSPC)': {t: Word ‚å´}
    '&kp LG(LEFT)': {t: Home}
    '&kp LG(RIGHT)': {t: End}
    '&kp LA(LEFT)': {t: Word ‚Üê}
    '&kp LA(RIGHT)': {t: Word ‚Üí}
    '&kp LG(TAB)': {t: Last ‚ê£}
    '&kp LC(SPACE)': {t: Spotlight}
    '&kp LG(LC(Q))': {t: '$$mdi:lock$$'}
    '&kp C_VOL_UP': {t: '$$mdi:volume-plus$$'}
    '&kp C_VOL_DN': {t: '$$mdi:volume-minus$$'}
    '&kp C_MUTE': {t: '$$mdi:volume-mute$$'}
    '&kp C_PP': {t: '$$mdi:play-pause$$'}
    '&kp C_PREV': {t: '$$mdi:skip-previous$$'}
    '&kp C_NEXT': {t: '$$mdi:skip-next$$'}
    '&kp K_POWER': {t: '$$mdi:power$$'}
    '&kp C_SLEEP': {t: '$$mdi:sleep$$'}
    '&kp LC(Z)': {t: Undo}
    '&kp LC(X)': {t: Cut}
    '&kp LC(C)': {t: Copy}
    '&kp LC(V)': {t: Paste}
    '&kp LC(A)': {t: Sel All}
    '&kp LC(S)': {t: Save}
    '&kp LC(BSPC)': {t: Word ‚å´}
    '&kp K_LOCK': {t: '$$mdi:lock$$'}
    '&bootloader': {t: '$$mdi:progress-download$$', s: Boot}
    '&sys_reset': {t: '$$mdi:restart$$', s: Reset}
    '&lang_en': {t: EN}
    '&lang_ru': {t: RU}
    '&lang_ua': {t: UA}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ‚ñΩ
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: ‚åÉ
    right_ctrl: ‚åÉ
    left_shift: '$$mdi:arrow-up-bold$$'
    right_shift: '$$mdi:arrow-up-bold$$'
    left_alt: ‚å•
    right_alt: ‚å•
    left_gui: ‚ùñ
    right_gui: ‚ùñ
    keycode_combiner: '{mods}{key}'
    mod_combiner: '{mod_1}{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    # Modifiers
    LSFT: ‚áß
    RSFT: ‚áß
    LCTL: ‚åÉ
    RCTL: ‚åÉ
    LALT: ‚å•
    RALT: ‚å•
    LGUI: ‚ùñ
    RGUI: ‚ùñ
    # Navigation
    LEFT: ‚Üê
    DOWN: ‚Üì
    UP: ‚Üë
    RGHT: ‚Üí
    PGUP: PgUp
    PGDN: PgDn
    HOME: Home
    END: End
    BSPC: ‚å´
    DEL: ‚å¶
    ENT: ‚Üµ
    TAB: ‚á•
    ESC: Esc
    INS: Ins
    SPC: ‚ê£
    # Custom
    LANG_EN: EN
    LANG_RU: RU
    LANG_UA: UA
    CW_TOGG: CapsWord
    QK_BOOT: Boot
    QK_RBT: Reset
    F13: ‚éÑ
    # Layer activators
    'MO(SYMBOL)': {t: Symbol, type: layer-activator}
    'MO(NAV)': {t: Nav, type: layer-activator}
    'LT(FUNCTION,ESC)': {t: Esc, h: Function, type: layer-activator}
    'LT(MOUSE,ENT)': {t: ‚Üµ, h: Mouse, type: layer-activator}
    'TG(QWERTY)': {t: QWERTY, type: layer-activator}
    # Shortcuts
    'G(KC_L)': üîí
    'G(KC_TAB)': Last ‚ê£
    'C(KC_Z)': Undo
    'C(KC_X)': Cut
    'C(KC_C)': Copy
    'C(KC_V)': Paste
    'C(KC_A)': Sel All
    'C(KC_S)': Save
    'C(KC_Y)': Redo
    'C(KC_F)': Find
    'C(KC_BSPC)': Word ‚å´
    'C(KC_LEFT)': Word ‚Üê
    'C(KC_RGHT)': Word ‚Üí
    # Mouse
    MS_UP: ‚Üë
    MS_DOWN: ‚Üì
    MS_LEFT: ‚Üê
    MS_RGHT: ‚Üí
    MS_WHLU: Scrl ‚Üë
    MS_WHLD: Scrl ‚Üì
    MS_WHLL: Scrl ‚Üê
    MS_WHLR: Scrl ‚Üí
    MS_BTN1: LClick
    MS_BTN2: RClick
    MS_BTN3: MClick
    # Media
    'KC_VOLU': Vol +
    'KC_VOLD': Vol ‚àí
    'KC_MUTE': Mute
    'KC_MPLY': ‚èØ
    'KC_MPRV': ‚èÆ
    'KC_MNXT': ‚è≠
    'KC_PWR': ‚èª
    'KC_SLEP': Sleep
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    # Navigation
    BACKSPACE: '$$mdi:backspace$$'
    BSPC: '$$mdi:backspace$$'
    DELETE: '$$mdi:backspace-reverse$$'
    DEL: '$$mdi:backspace-reverse$$'
    TAB: '$$mdi:keyboard-tab$$'
    RETURN: '$$mdi:keyboard-return$$'
    RET: '$$mdi:keyboard-return$$'
    ENTER: '$$mdi:keyboard-return$$'
    ESCAPE: '$$mdi:keyboard-esc$$'
    ESC: '$$mdi:keyboard-esc$$'
    SPACE: '$$mdi:keyboard-space$$'
    SPC: '$$mdi:keyboard-space$$'
    UP: '$$mdi:arrow-up$$'
    DOWN: '$$mdi:arrow-down$$'
    LEFT: '$$mdi:arrow-left$$'
    RIGHT: '$$mdi:arrow-right$$'
    HOME: '$$mdi:arrow-collapse-left$$'
    END: '$$mdi:arrow-collapse-right$$'
    PAGE_UP: PgUp
    PG_UP: PgUp
    PAGE_DOWN: PgDn
    PG_DN: PgDn
    # Modifiers
    LSHIFT: '$$mdi:arrow-up-bold$$'
    LSHFT: '$$mdi:arrow-up-bold$$'
    RSHIFT: '$$mdi:arrow-up-bold$$'
    RSHFT: '$$mdi:arrow-up-bold$$'
    LCTRL: ‚åÉ
    LALT: ‚å•
    LGUI: ‚ùñ
    RCTRL: ‚åÉ
    RALT: ‚å•
    RGUI: ‚ùñ
    CAPSLOCK: Caps
    CAPS: Caps
  zmk_combos: {}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
