name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  glove80:
    uses: moergo-sc/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: glove80/build.yaml
      config_path: glove80
      artifact_name: glove80-firmware

  glove80-34k:
    uses: moergo-sc/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: glove80_34k/build.yaml
      config_path: glove80_34k
      artifact_name: glove80-34k-firmware
